spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tcms?characterEncoding=utf8
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  jackson:
    default-property-inclusion: non-empty
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false